services:
  rabbitmq:
    image: rabbitmq:3
    container_name: some-rabbit
    hostname: my-rabbit

  rabbitmq-management:
    image: rabbitmq:3-management
    container_name: rabbitmq-service
    hostname: rabbitmq-service
    networks:
      - restaurante-bridge
    ports:
      - "15672:15672" # Porta do Management UI
      - "5672:5672"   # Porta do protocolo AMQP

  mysql:
    image: mysql:5.6
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: restaurantedb
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - restaurante-bridge

  item-service:
    build:
      context: ./ItemService
    image: itemservice:1.2
    container_name: item-service
    ports:
      - "8080:80"
    networks:
      - restaurante-bridge
    depends_on:
      - mysql
      - rabbitmq-management

  restaurante-service:
    build:
      context: ./RestauranteService
    image: restauranteservice:1.5
    container_name: restaurante-service
    ports:
      - "8081:80"
    networks:
      - restaurante-bridge
    depends_on:
      - mysql
      - rabbitmq-management

networks:
  restaurante-bridge:
    driver: bridge